sergiocorreia/panflute

panflute/tools.py
Don't know why the previous notation produces a SyntaxError on my Python version (3.4.3 win32).
=> Fix debug function (** argument convention)

panflute/io.py
This change is backwards compatible with Py2 and Py3. `json.dump` apparently has bugs in Py2 when dealing with unicode, whereas `json.dumps` works correctly in both Python2 and Python3. See [StackOverflow](http://stackoverflow.com/a/34574105/5451769) for reference.
=> Use json.dumps instead of dump for Py2 compatibility

.travis.yml
Fix issue #16.
The reason travis was failing is because travis' container-based distro is Ubuntu 12.04, so it actually is using `pandoc_1.9.1.1-1_amd64.deb`!
However, the container-based VM is still the best option because of boot time (a few seconds!). Here I use wget to install the binary from GitHub directly.
The build is now also build against 2 different versions of pandoc. You can add as many as you want, but note that the current build time of this 7X2 builds is about 4 minutes.
I guess the most important versions of pandoc to check would be these 2 since the JSON output has recently been changed in 1.18, right?
=> Travis CI: build against pandoc 1.17.2, 1.18

panflute/elements.py, setup.py
We no longer depend on "t" being before "c" (or anything like that).
This is a more general fix that the one applied by 2686e76
EG: we expect to see {"t":"Str","c":"x"}
But that's not a guarantee and could change in the future
This should make panflute *a bit* slower
=> Stop depending on the order of the JSON input

.travis.yml, requirements.txt, setup.py
Since you use Windows and use GitHub Desktop, I figure it would be easier for you to let Travis deploy to PyPI *everytime*. Only when the version is bumped, it will go through. So effectively Travis will auto deploy to PyPI whenever you change the version and commit. (If the version isn't changed, it won't go through. There's an error but since it is in the deploy stage, the error won't result in a fail build.)
What's done:
- setup Travis' deploy to PyPI
- I also rearrange the `.travis.yml` into a more logical order.
- `setup.py` and `requirements.txt` are setup; in particular, travis can now install the dependency by `pip install -e .[test]`
Because I don't have your PyPI password, you need to go into <https://travis-ci.org/sergiocorreia/panflute>:
```
More Options -> Settings -> …
```
=> setup travis to always deploy on PyPI (#22)

.travis.yml
Continue from [setup travis to always deploy on PyPI (#22) by ickc · Pull Request #24 · sergiocorreia/panflute](https://github.com/sergiocorreia/panflute/pull/24#pullrequestreview-9957924):
I forgot to update the `$pandocVersion` I committed last time. I should have changed it as well, like in this commit.
I see that you have already patched it to make it work. So this patch is really optional. The way I did it uses bash's parameter expansion and is a bit cleaner.
=> fix pull request #24

.travis.yml
Currently, if there's some other branch that incremented the version so that it is bigger than the one in PyPI, it will "accidentally" deployed that branch to PyPI.
=> travis: deploy on master only

panflute/base.py, panflute/containers.py, panflute/elements.py, panflute/io.py, panflute/tools.py
After this commit, a search on the keyword "py2" will find the lines that matter to py2 only. It will be easier to cleanup when py2 support is dropped.
=> Py2 refactoring: minimize the footprint of py2 code

.travis.yml, setup.py, tests/requirements.txt
1. travis can test the validity of the README.rst.
- It is for PyPI’s README, since an invalid rst will be shown as plain text over PyPI.
- a failure on rst2html conversion will *not* fail the whole build. But it will be useful to check for errors in Travis when one see the PyPI's README is plaintext.
2. It also removes the extra dep on pypandoc
=> README.rst: create by pandoc rather than pypandoc

panflute/elements.py
Current versions of Pandoc have one more block format in addition to 'tex', 'html' and 'latex' -- namely, 'context'. If this isn't handled, it becomes impossible to use raw blocks with ConTeXt output.
See https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/ConTeXt.hs#L178
=> Add missing raw block format.

panflute/base.py, panflute/elements.py
I noticed bug similar to #15, but in my case the content of header was empty ListContainer.
I convert HTML to custom lua writer using panflute filter.
If source html has table without headers (table>tbody>tr>...), panflute will produce for header TableRow with empty ListContainter. That triggers IndexError.
The change in base.py was necessary as not defined `ans` used in following `setattr(self, child, ans)`.
=> Fix IndexError on Table header if value is empty TableRow(ListContainer())

.travis.yml
latest now points to pandoc 2.0, i.e. its test is passed automatically.
(No new elements are added. So I guess nothing else needed to be done to support pandoc 2.0?)
=> Tweak .travis.yml; pandoc 2.0 test passes

panflute/elements.py
`icml` is a valid format for `RawBlock`s (there may be more of them, but I couldn't find a list).
=> Formats for RawBlocks

panflute/elements.py
This commit allows `builtin2meta` to convert `str` to `MetaSting` as
well as recursively converting `list`s and `dict`s.  The original
implementation handled conversion of native `float`, `bool`, and `int`
variables, but did not consider `str`.  On the container side, `list`
and `dict` variables simply passed the item through to `MetaList` and
`MetaMap` respectively.  This tacit assumed the contents was already a
`MetaValue` meaning constructs such as
doc.metadata["references"] = doc.get_metadata("references")
would fail with a `TypeError`.
=> Convert more builtins to MetaValues

examples/panflute/comments.py
I tried [comment.py](https://github.com/sergiocorreia/panflute/blob/master/examples/panflute/comments.py) to practice panflute, but it did not seem to work.
After reading API, I think the `format` attribute of `el` instead of that of `doc` should be matched to "html". The change works for me.
--
This is my first pull request. I read through the contributing guidelines but did not find rules about examples. Apologize if I disturb.
=> fix panflute example comment.py

panflute/containers.py
Modifies `ListContainer.__setitem__` so that it will recognize and properly handle slice assignments.
Python's language reference [isn't quite clear](https://docs.python.org/3/reference/simple_stmts.html#assignment-statements) on what `__setitem__` is supposed to receive during a slice assignment, but the behavior assumed here (receiving a `slice` object as the index and the value unchanged) seems to be standard.
=> Add support for slice assignment to ListContainer

panflute/base.py, panflute/containers.py, panflute/elements.py, panflute/io.py, panflute/tools.py, panflute/utils.py
- elements.from_json now expects dict input rather than list of tuples
- io.load calls json.load with object_hook instead of object_pairs_hook
- removes all traces of OrderedDict
Because we're now support Python 3.6+ only, and dict in both CPython and pypy 3.6+ is now guaranteed to be ordered (it is an implementation detail in 3.6, guaranteed in 3.7+, so all 3.6+'s dict are ordered)
**It avoids json.loads packing them in list of tuples and panflute converting it back to dict in elements.from_json**
=> remove object_pairs_hook and OrderedDict

.github/workflows/run_tests.yml, setup.py
This PR add pypy3 test, and also test against multiple pandoc versions.
May not be ready to merged if discussion of supported pandoc versions is needed. By the way, is it mentioned somewhere in the doc which pandoc versions are supported?
By the way, the run test and publish workflow can be combined into one. E.g. setup in <https://github.com/ickc/pantable/blob/master/.github/workflows/pythonpackage.yml>.
Edit: seems like pandoc v1 support is dropped as shown in <https://github.com/ickc/panflute/runs/676485536>.
Edit2: pypy3 is added because it is stated as a supporting platform in `setup.py`.
Edit3: from [CI](https://github.com/ickc/panflute/actions/runs/105202745) seems like only down to pandoc 2.7 is supported.
=> run_tests.yml: test against multiple pandoc versions

.github/workflows/run_tests.yml
because GitHub API has very low rate limit if not autheticated. Autheticate for the sake of using GitHub API doesn't feel right.
While using the API sounds more stable, the regex approach has been used since 2016 without a hiccup.
c.f. https://github.com/ickc/pancritic/issues/13, #139, #147
=> run_tests.yml: revert to use regex instead of GitHub API

tests/sample_files/native/README.md, tests/sample_files/native/nordics.native, tests/sample_files/native/planets.native, tests/sample_files/native/students.native
c.f. jgm/pandoc#6888
**Do not merge yet!**
By commit 243af317, the `pandoc/test/tables/*.native` are copied to `panflute/tests/sample_files/native/*.native`. But it suddenly occurred to me there's a **licensing issue** here. Since pandoc is GPLv2+ we can't just copy their files here, which is BSD-3-Clause License.
A few possible ways to resolve this:
- I checked the commit history in pandoc, all the 3 native files are committed by @tarleb, so may be it is sufficient to ask tarleb for permission to dual license it for panflute?
- In general, `pandoc/test` would be a gold mine for anyone writing anything supporting pandoc in anyway (such as a 3rd party pandoc-types, parsers, etc.), so dual licensing everything in `pandoc/test` would be very useful as many of these 3rd parties are not …
=> tests/sample_files/native/*.native: normalized

setup.py
Just a preventive measure, no need to make release for this.
=> setup.py: make sure all run dep are constrained within a major version

panflute/tools.py
two fold:
- provide option to control pandoc_path when used as a library
- in principle faster since "which" is called once and cached, so multiple call to them has reduced latency
=> tools.py: convert_text, run_pandoc add pandoc_path option

.github/workflows/run_tests.yml, setup.py
c.f. #173
I tested various pyyaml and click versions in https://github.com/ickc/panflute/actions/runs/441717836
As they pass, we expand the allowed versions in setup.py
Also remove the python<4 constraint as there's no plan for its arrival yet.
=> Improve dep version constraints

.github/workflows/publish.yml, .github/workflows/run_tests.yml, CONTRIBUTING.md, README.md, docs/source/install.rst, panflute/autofilter.py, panflute/tools.py, panflute/version.py, setup.py
The develop branch currently contains minor PRs that is (hopefully) non-controversial and backward compatible. It is created to be merged during release phase so that the author can batch review this.
This PR includes:
- #174
- #175
- #176
- #179
- #185
- #186
And among those, these are slightly less trivial and should be looked at more carefully:
- #174: convert_text, run_pandoc add pandoc_path option
- #185: Support pandoc 2.12+, which adds PandocVersion to put all `pandoc --version` related operations together and call pandoc only once
Edit: This PR also add pandoc 2.12+ support hence bump panflute version to 2.1.0.
=> Support pandoc 2.12+

setup.cfg
When running `python setup.py test` I was getting the following error:
> /usr/lib/python3.9/site-packages/setuptools/dist.py:691: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
In the interest of keeping the output clean so any future warnings that actually matter stand a chance of getting noticed, I suggest just doing what it wants.
=> Fix build time warning from setuptools

.github/workflows/run_tests.yml, setup.py
Note Arch packaging has been using this against Click v8 for some time,
the requirements file doesn't specify versions at all and only the test
function was failing because of this version locking.
=> Don't block Click v8, seems to work fine

.github/workflows/run_tests.yml, README.md, panflute/version.py
Summary:
- document the support of pandoc 2.14
- add badges,
- add info on distributed versions on GitHub Releases, conda-forge. Ideally, these 3 versions should be consistent. See <https://github.com/sergiocorreia/panflute/pull/193#issuecomment-860027299>.
- add license
=> panflute 2.1.2 release

docs/source/code.rst, panflute/elements.py, panflute/io.py, panflute/tools.py, tests/test_walk.py
- Adds tests/test_walk.py, which tests the behavior I document below
- Adds the following rule for action functions to docs/source/code.rst:
> If the received element is a block or inline element, they may return a list of elements of the same base class, which will take the place of the received element.
- Various spelling and capitalization fixes to documentation
We may want to consider allowing lists of MetaValues to be returned, though in my opinion it makes more sense to return a MetaList in those situations.
In #199, @ickc suggested that if action functions return a single element, that element should always be in a list, and that we should only allow standalone elements to be returned for compatibility reasons. Because of the difference between Block/Inline and MetaValue lists I …
=> Test and document list returning behavior for action functions

.github/workflows/run_tests.yml, README.md, panflute/version.py, setup.py, tests/filters/assert_env.py
- fix a test failure related to change in `PANDOC_READER_OPTIONS` with pandoc 2.16+
- support Python 3.10
- allow pyyaml 6: [pyyaml/CHANGES at master · yaml/pyyaml](https://github.com/yaml/pyyaml/blob/master/CHANGES)
- have a more sophisticated GitHub Actions matrix to test all supported versions, using the include syntax: [Workflow syntax for GitHub Actions - GitHub Docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix)
Notes:
pandoc 2.16 release summary: [Release pandoc 2.16 · jgm/pandoc](https://github.com/jgm/pandoc/releases/tag/2.16)
Running `python tests/test_env.py`,
```markdown
- Testing Doc() created by panflute:
- No environment vars; as expected
- Testing Doc() created by panflute.convert_text(): …
```
=> panflute v2.1.3: Support pandoc 2.16 & upgrade dependencies

.github/workflows/run_tests.yml, panflute/tools.py
Edit: note that panflute only calls pyyaml when using `yaml_filter` (yaml in code block) so this only changes the order of reading the YAML metadata inside that code block. Ordering is nice when round-trip is needed, i.e. a filter convert from yaml code block, and another filter convert it back.
by using yamlloader whenever available.
See doc in https://github.com/Phynix/yamlloader
>an OrderedDict loader/dumper is implemented, allowing to keep items order when loading resp. dumping a file from/to an OrderedDict (Python 3.7+: Also regular dicts are supported and are the default items to be loaded to. As of Python 3.7 preservation of insertion order is a language feature of regular dicts.)
Note: while yamlloader is not very popular, I've been using it in all of my projects (including some …
=> Optionally ordered yaml

panflute/autofilter.py, panflute/base.py, panflute/io.py, panflute/tools.py, panflute/version.py
- `walk()` method now accepts a `walk_inlines=True` argument. If set to False, panflute will only walk through the block elements and not through the deeper inline elements, so the filter runs much faster.
- This change is also propagated to the `run_filter()` and run_filters()` functions.
- Fixed typos in documentation and tweaked an error message.
=> Minor fixes and improvements

panflute/table_elements.py
The Table class `__init__` function defaults to setting the caption parameter to `None`:
https://github.com/sergiocorreia/panflute/blob/354297b90b763f99dee270b9e180baa21187cd64/panflute/table_elements.py#L69-L70
However, creating a Table with `caption=None` currently throws an error. This PR allows for the caption parameter to equal `None`.
I would be happy to write a test for this if you feel it would be appropriate.
Addresses #209, and possibly #206.
=> Allow Table class to have no caption

docs/source/install.rst
I don't think git+git is a valid protocol. Either way, it didn't work for me, and the more common git+https did!
=> Fix install from github URL

panflute/base.py, panflute/containers.py, tests/test_regressions.py
Hi, I solved the issue described in #223 using this patch locally. With this adaption I was able to run my filter as expected.
Also added a smaller test than in the ticket.
Idea is to fill the index position in the ListContainer along with the parent and location instead of deriving it.
Like this __eq__ on element can be left untouched.
=> Added fix for unstable element index (issue #223)

README.md
The README file lacks recent panflute/pandoc versions.
CI tests run on pandoc:latest so I guess it is okay to say pandoc 2.19.x is supported?
There has not been many changes in pandoc-types. There is this one that I'm not sure about the implications for panflute compatibility : https://github.com/jgm/pandoc-types/commit/b084b2af7151d2d9ae84b7f558f2a77c5103cdd7
=> Document pandoc 2.19 support

panflute/elements.py
It seems there is already an attempt to make the interaction with `MetaMap`/`MetaList` as transparent as interacting with regular dict/list while under the hood calling `builtin2meta()`, but it wasn't fully functional.
This PR complete the implementation by properly implementing `MutableMapping` for `MetaMap`, and `MutableSequence` for `MetaList`.
=> [Metadata] Make MetaMap/List completely pythonic

panflute/elements.py, panflute/table_elements.py
Fixes https://github.com/sergiocorreia/panflute/issues/229
=> Figure, Table: fix to_json() crash if caption is None
